spring:
  application:
    name: TeknoyCart Backend
  config:
    import: optional:classpath:application-local.yml
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${SPRING_MAIL_USERNAME:clarencekirkmc@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.chmtvasbhkbrvydbajnd}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Ensures no overwrite of existing Capstone 1 Supabase tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:YOUR_JWT_SUPER_SECRET_KEY_FOR_TEKNOYCART_TOKEN_GENERATION_MINIMUM_256_BITS}
  expiration: 86400000 # 24 Hours in milliseconds

brevo:
  api:
    key: ${BREVO_API_KEY}

supabase:
  url: ${SUPABASE_URL:https://chmtvasbhkbrvydbajnd.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobXR2YXNiaGticnZ5ZGJham5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3NjMwMDgsImV4cCI6MjA5NTMzOTAwOH0.IJJIrh-dr4xRoXPPeBJoN_pVVHrNY4db5E1VY1Czj3I}

